/* tslint:disable */
/* eslint-disable */
/**
 * SampleAPI
 * サンプルののAPI定義です。 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ApiError,
    ApiErrorFromJSON,
    ApiErrorFromJSONTyped,
    ApiErrorToJSON,
} from './';

/**
 * APIエラーレスポンス
 * @export
 * @interface ApiErrorResponse
 */
export interface ApiErrorResponse {
    /**
     * HTTPステータスコード
     * @type {number}
     * @memberof ApiErrorResponse
     */
    code: number;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof ApiErrorResponse
     */
    message: string;
    /**
     * エラー詳細
     * @type {Array<ApiError>}
     * @memberof ApiErrorResponse
     */
    errors: Array<ApiError>;
}

export function ApiErrorResponseFromJSON(json: any): ApiErrorResponse {
    return ApiErrorResponseFromJSONTyped(json, false);
}

export function ApiErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiErrorResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'code': json['code'],
        'message': json['message'],
        'errors': ((json['errors'] as Array<any>).map(ApiErrorFromJSON)),
    };
}

export function ApiErrorResponseToJSON(value?: ApiErrorResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'code': value.code,
        'message': value.message,
        'errors': ((value.errors as Array<any>).map(ApiErrorToJSON)),
    };
}


