/* tslint:disable */
/* eslint-disable */
/**
 * SampleAPI
 * サンプルののAPI定義です。 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * APIエラー
 * @export
 * @interface ApiError
 */
export interface ApiError {
    /**
     * エラー対象
     * @type {string}
     * @memberof ApiError
     */
    target?: string;
    /**
     * エラーコード
     * @type {string}
     * @memberof ApiError
     */
    errorCode: string;
    /**
     * エラーメッセージ
     * @type {string}
     * @memberof ApiError
     */
    errorMessage: string;
}

export function ApiErrorFromJSON(json: any): ApiError {
    return ApiErrorFromJSONTyped(json, false);
}

export function ApiErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'target': !exists(json, 'target') ? undefined : json['target'],
        'errorCode': json['errorCode'],
        'errorMessage': json['errorMessage'],
    };
}

export function ApiErrorToJSON(value?: ApiError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'target': value.target,
        'errorCode': value.errorCode,
        'errorMessage': value.errorMessage,
    };
}


