/* tslint:disable */
/* eslint-disable */
/**
 * SampleAPI
 * サンプルののAPI定義です。 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * メンバー登録フォーム
 * @export
 * @interface PostMemberForm
 */
export interface PostMemberForm {
    /**
     * メールアドレス
     * @type {string}
     * @memberof PostMemberForm
     */
    email: string;
    /**
     * パスワード
     * @type {string}
     * @memberof PostMemberForm
     */
    password: string;
}

export function PostMemberFormFromJSON(json: any): PostMemberForm {
    return PostMemberFormFromJSONTyped(json, false);
}

export function PostMemberFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): PostMemberForm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function PostMemberFormToJSON(value?: PostMemberForm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}


