/* tslint:disable */
/* eslint-disable */
/**
 * SampleAPI
 * サンプルののAPI定義です。 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Member,
    MemberFromJSON,
    MemberFromJSONTyped,
    MemberToJSON,
} from './';

/**
 * ログインAPIのレスポンス
 * @export
 * @interface SigninResponse
 */
export interface SigninResponse {
    /**
     * 
     * @type {Member}
     * @memberof SigninResponse
     */
    profile: Member;
}

export function SigninResponseFromJSON(json: any): SigninResponse {
    return SigninResponseFromJSONTyped(json, false);
}

export function SigninResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SigninResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'profile': json['profile'],
    };
}

export function SigninResponseToJSON(value?: SigninResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'profile': value.profile,
    };
}


