/* tslint:disable */
/* eslint-disable */
/**
 * SampleAPI
 * サンプルののAPI定義です。 
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    ApiErrorResponse,
    ApiErrorResponseFromJSON,
    ApiErrorResponseToJSON,
    PostMemberForm,
    PostMemberFormFromJSON,
    PostMemberFormToJSON,
    SigninResponse,
    SigninResponseFromJSON,
    SigninResponseToJSON,
} from '../models';

export interface RegisterMemberRequest {
    postMemberForm: PostMemberForm;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * サンプル
     */
    async registerMemberRaw(requestParameters: RegisterMemberRequest): Promise<runtime.ApiResponse<SigninResponse>> {
        if (requestParameters.postMemberForm === null || requestParameters.postMemberForm === undefined) {
            throw new runtime.RequiredError('postMemberForm','Required parameter requestParameters.postMemberForm was null or undefined when calling registerMember.');
        }

        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/sample`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PostMemberFormToJSON(requestParameters.postMemberForm),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => SigninResponseFromJSON(jsonValue));
    }

    /**
     * サンプル
     */
    async registerMember(requestParameters: RegisterMemberRequest): Promise<SigninResponse> {
        const response = await this.registerMemberRaw(requestParameters);
        return await response.value();
    }

}
